### PR TITLE
adding visualisations and outliers

### LINKED ISSUE #1: visualisations and outliers

### PR DESCRIPTION
**Pull request by Favour-Yahdii**

### CODE REVIEW

**Review by obinnaofomah — COMMENTED** [review]
Nice shot @Favour-Yahdii on the Outliers removal. Being curious, I have a couple of questions with respect to the outlier handling.

1. Are they valid data points? If yes, don't you think we are trying to assume an ideal state, other than factoring some elements of noise to model reality? Recall that the sensitivity of some models to outliers is quite minimal.

2. I am curios to know why outliers were removed from only four (4) columns, or does these features offer more significance to the problem-statement than the others?

I will appreciate your thoughts on this.

**Comment by Favour-Yahdii** [comment]
Hi Obinna,
So the process of handling outliers isn't complete yet. The four variables
were handled because it is easier to understand outliers in variables like
height and weight than in variables like 'how many fruits and vegetables
were consumed'. Also, the outliers were not dropped but replaced with the
median.

I agree with the robustness of some models to outliers hence the imputation
of only certain easy to understand columns. A suggestion could be to run
the model with and without the outliers and see the impact if any.

Thanks for the review.

Kind regards,
Favour

**Comment by obinnaofomah** [comment]
I think I agree with you on investigating the model performance with and without the outliers. That would inform us better on the next strategy.

**Comment by Favour-Yahdii** [comment]
That's great! Are you the one handling modelling? I can't remember who
Temitope assigned it to.

**Pull request merged**
